#
# put this file in the parent folder of both backend and frontend repositories
#
services:
  db:
    image: mysql:9.3
    container_name: spf-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: backend_api
    volumes:
      - spf-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./backend
    image: spf-backend:latest
    container_name: spf-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:@db:3306/backend_api
      JWT_SECRET: "LFLGGMLBNVDFSVDNPBCVKWCCPJMVMZBQMJCVEUTDJBLFUV2FGR3VUVSFO5JTETLZMFEEE2LCNV2E6UJSGB4GI3KJPFHEKNKEMJKTK32ZGBSEOYKXJJEFMVJVIRRFMSLYLF5E4USUNNHHKVLNPBVGE23QO5NEKYZVMVLVMUSNIV2GUYSWLI3FURLIJNQUORSYJZCTKRDCKVNHAV2WMRHWG22SKJRUQVS2K5CXANKZNJHGUVDLJZ2FE2SGNNJDE2BSLEZDC42NI5LFETKFORVWEVS2GZNEKRLXKMYWYWCOLBBGSVRQLF3VO3DEKJKGWTTUKJXFE22XIU2XGV3LIV3VGMLMLFKWUQTBKZ5FK52ZKZRTKZCVKJJGGRCOMFLDCRSPKEZDC23BI5DFQTSFGVCGE3KSO5MWWZCTMJDU45COK54GUTJQGFHVCMRRO5GVM4CIMJDXA2CWPJVXQWJTMN3VGMLQLBLW2MLIKYYDK52XNRRTCTKFKJJGGRCCLJLUKRSPKEZDCT3BI5HESVLKIZVGEVSWJ5ITEMKLJVLU45COIU2UIYSVLJYFOVTDGFQTESLZJZLXQYKRKRBEYV2UJE2WI3KGGNGUK5DBMJKVUMKXNZRXOUZSJV5FC3LINJRFQTSPKEZDK23BI5JHIVSVGVCGE3CKO5LWUSTPJVDHA5DCJBYGWURRLJZFERSGO5SFM3CZKVVEM2TCKVNHUUSGIZ3WEV2GLFRUIWSFKVMEE4KZKVSHGZBQKJJGGSCGNNLDCSTVK5WEK52TGJHHIVTOKJNFMM2SONJEMRTXMQZES6SVKU2UIYSVLI2VS2SJPBQUOUSIMJDXARKVLBBHUWSGMMYWC3KGIJGUK5C2MJLXQNKXNNCXOUZROB2E6WDMMFGWYWLXKJDEM53FKZYFSUTKIZQVORJUO5JEMRTXMVWUMSDCIRFGCV2FOB3VS3JRNJKGWTTVKVWWQ2KSGNHE6UJSGFFU2V2WOVRDANKEMJKVU6SZNNRTKTJQKJJGGSDELJLUKSTTLEZGG52TGJJFSVDNPBCVKWCCGZMTA2CXMVLUMWCPKRDGUZD2IJGFS6SOKNREM4CZKFKTKRDCKVNDCWLNGA2U2V2KORKG26CFKVLTQOI==="
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    image: spf-frontend:latest
    container_name: spf-frontend
    depends_on:
      - backend
    environment:
      BACKEND_API_URL: http://backend:3000/api
      SESSION_SECRET: "C5BJAQJ1B176OH2HE1PM2LRKDH252S3LB5C4SC35A4O4MOPID1O64RJB9P1MQCBMC8P38JI3DL76GOQ78PKM4HQL9P1MQKHHCCPL2JI3DP96OORE99O68HPPF5IL2C2BCDMLCUJ49156GOAN6H746RA6D5CLEJJI8H8N0TAPB157IOHJCD746RA665I4EQ3MCDMMOC35A4O4MP3DAPT68G9G9DCLEDBGC9BKCC2QAT8KSGRD8PQ68M2EDHD42C2BB5C54C2QASQJ0OAN75QK8KBG6DD5EKAE8DMM8Q31ASQ4SGRECHO64HQIDHHMQDBCCCPKQJI3DLO32MI7DHL62LPP65HNEC2BB9BLKRB1AT770MIN6KO48KBG61CLGGAE8DMKSQ3391932ORDAL746RAA65HMQD2E8DMKCQAPASQMMOHI6LM5KG9G9DCJ4EBMC5RJ0IQQDL37AMJN615M6CQ2D1HMQSQE8DN68Q34DLAKSGREA9O5KCJ861D6QR3QCH3LCQQ4A5O7AMAOA8OM6RA6ED252S3DC5C70DI4A5O6KOA7DHRK8KBGE5I5EKJEB98J0IR3DLB78MANEHM48KBGETH36KAE8DMKCUB268OMGP27DHL48KBGEDI5EDBAC50J0IQPDLM7IMI1615LKR9PF5D34LHG8H8N0UAQB1332MIO9OO48KBGF9GKER1IB9C4KS32DLHKSGREA9K64HRJ9P1MQIHHCLN6UJI3DL376OI774PK8KBGETCLGGJCCDJJ0IR4B176OH2HE1T66I2MF5GLEE9HCDRJ0IR36D96OMIO85746RA6ELH6QE9HC9MKSR24A5NJQ==="
    ports:
      - "4000:4000"

volumes:
  spf-db-data:
